export const CRUD_ACTION_TYPES = {
  ADD_CONTACT: "ADD_CONTACT",
  DELETE_CONTACT: "DELETE_CONTACT",
  UPDATE_CONTACT: "UPDATE_CONTACT",
  GET_CONTACTS: "GET_CONTACTS",
  GET_CONTACT: "GET_CONTACT",
};
