export const BLOGS_ACTION_TYPES = {
  SET_BLOGS: "blog/SET_BLOGS",
};

// export const BLOGS_ACTION_TYPES = {
//   FETCH_BLOGS_START: "blog/FETCH_BLOGS_START",
//   FETCH_BLOGS_SUCCESS: "blog/FETCH_BLOGS_SUCCESS",
//   FETCH_BLOGS_FAILED: "blog/FETCH_BLOGS_FAILED",
// };
