export const BLOGS_ACTION_TYPES = {
  SET_BLOGS_MAP: "SET_BLOGS_MAP",
};

// export const BLOGS_ACTION_TYPES = {
//   FETCH_BLOGS_START: "blog/FETCH_BLOGS_START",
//   FETCH_BLOGS_SUCCESS: "blog/FETCH_BLOGS_SUCCESS",
//   FETCH_BLOGS_FAILED: "blog/FETCH_BLOGS_FAILED",
// };
